### ISSUE TITLE
ユーザーごとの録画ライブ保存に対応する

### ISSUE THREAD

**Issue by guredora403** [actlaboratory/ULTRA#24]

**Comment by kitabatake1013** [comment]
この機能がどうしても必要だったので作ってみた。
エラーチェックはこれから。

**Comment by kitabatake1013** [comment]
現状の仕様
* 合い言葉で保護されたムービーは録画しない
    * 合い言葉で保護された録画が複数ある場合に、どれを録画しようとしているのかユーザが判別できないため
    * どうしても録画したければ、これまで通り再生ページを直接指定する
* 保存先に対象ファイルが既にあれば、録画をスキップする
    * 本ソフトで対象ライブを既に録画している場合に、同じ内容のファイルを複数作ることになるため
    * ただし、リアルタイムに録画したものは頭が切れることがわかっている
    * 上記の理由からあえて再度録画したいなら、事前に該当ファイルを削除しておくか、再生ページの指定によって録画する

**Comment by yamahubuki** [comment]
実装済み
