### ISSUE TITLE
WSSのプロキシ対応

### ISSUE THREAD

**Issue by kitabatake1013** [actlaboratory/ULTRA#4]
ソケット通信を確立するときに、引数としてプロキシサーバーの情報を指定する必要があるらしい。

**Comment by yamahubuki** [comment]
os.environ['HTTPS_PROXY']を参照してください。
server:portです。
サーバ名は、IPアドレス(v4またはv6)の可能性があります。
ポート番号は省略がないとも言い切れません。(省略時何番なのかは知らないが…)

環境変数でユーザも変更できる場所なので、値をバリデーションしてから使ってください。

セットできた場合と、値が存在したにもかかわらず設定に失敗した場合(バリデーションエラー等)はログに出してください。

**Comment by kitabatake1013** [comment]
動作確認してクローズします。
