### ISSUE TITLE
yt-dlpでのエラー発生時の対処

### ISSUE THREAD

**Issue by yamahubuki** [actlaboratory/ULTRA#42]
yt-dlpにてエラー発生時、引きずられてULTRAも落ちてしまうことがあるので修正する。
外套のエラーログは下記。

Traceback (most recent call last):
  File "app.py", line 102, in run
  File "sources\ydl.py", line 350, in run
AttributeError: 'NoneType' object has no attribute 'is_alive'

**Comment by kitabatake1013** [comment]
@yamahubuki 報告ありがとうございます。
修正したつもりですが、直っているか確認をお願いします。

**Comment by yamahubuki** [comment]
@kitabatake1013 
後ほど確認いたします。
本件、yt-dlp側のエラーダイアログが出ないための対策も必要と思います。
対策可否含めて確認お願いします。

**Comment by kitabatake1013** [comment]
@yamahubuki ご指摘の点をさらに修正しました。
問題がなければ更新履歴を加筆してクローズします。

**Comment by yamahubuki** [comment]
@kitabatake1013 動作に問題がないことを確認しました。対応ありがとうございます。
