### ISSUE TITLE
設定画面の作成

### ISSUE THREAD

**Issue by kitabatake1013** [actlaboratory/ULTRA#6]
NPCと共通する部分はそのまま使う。
加えて、

- 通知設定
- 録画設定

は作る必要がある。

**Comment by yamahubuki** [comment]
@kitabatake1013 
保存先ディレクトリ指定に参照ボタンがないのでダミーのボタンをつけておきました。
動作するよう調整してください。
レイアウトは完了しているので、参照ボタンが動作次第クローズして大丈夫です。
